name: Cargo Publish

on:
  push:
    branches:
      - 'releases/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: crates.io
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        with:
          command: publish
          args: --dry-run
