name: Cargo Publish

on:
  push:
    branches:
      - 'release'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: crates.io
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - uses: actions-rs/toolchain@11bd71901bbe5b1630ceea73d27597364c9af683 #v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 #v1.0.3
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        with:
          command: publish
